import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import Client from "./client";
import { Paper } from "@mui/material";


export const metadata: Metadata = {
  title: "Trading",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <Client>
            <Paper sx={{width: '100vw', height: '100vh'}}>
            {children}
            </Paper>
          </Client>
        </AppRouterCacheProvider>  
      </body>
    </html>
  );
}
